[package]
name = "bevy_enhanced_input"
version = "0.8.0"
authors = ["Hennadii Chernyshchyk <genaloner@gmail.com>"]
edition = "2024"
description = "Dynamic and contextual input mappings for Bevy"
readme = "README.md"
repository = "https://github.com/projectharmonia/bevy_enhanced_input"
keywords = ["bevy", "input"]
categories = ["game-development"]
license = "MIT OR Apache-2.0"
include = ["/src", "/LICENSE*"]

[dependencies]
bevy_enhanced_input_macros = { path = "macros", version = "0.8.0" }
bevy = { version = "0.16.0-rc", default-features = false, features = ["std", "bevy_log", "serialize"] }
bevy_egui = { git = "https://github.com/slyedoc/bevy_egui.git", branch = "bevy_0.16", default-features = false, optional = true }
#bevy_egui = { version = "0.33", default-features = false, optional = true }
serde = { version = "1.0", default-features = false, features = ["derive"] }
bitflags = { version = "2.6", features = ["serde"] }
variadics_please = "1.1"

[dev-dependencies]
bevy = { version = "0.16.0-rc", default-features = false, features = [
  "bevy_gilrs",
  "bevy_gizmos",
  "bevy_window",
  "bevy_picking",
  "default_font",
  "std",
  "x11",
] }
ron = "0.9"

[features]
default = ["ui_priority"]

# Prioritizes 'bevy_ui' actions when processing inputs.
ui_priority = ['bevy/bevy_ui']

# Prioritizes 'egui' over actions when processing inputs.
egui_priority = ['dep:bevy_egui']

[[example]]
name = "ui_priority"
required-features = [
  "ui_priority",
  "egui_priority",
  "bevy_egui/render",
  "bevy_egui/default_fonts",
]

[lints.clippy]
type_complexity = "allow"
alloc_instead_of_core = "warn"
std_instead_of_alloc = "warn"
std_instead_of_core = "warn"

[workspace]
members = ["macros"]
